# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import goServer_pb2 as goServer__pb2


class GoTestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTestGO = channel.unary_unary(
                '/goServerTest.GoTestService/GetTestGO',
                request_serializer=goServer__pb2.TestRequest.SerializeToString,
                response_deserializer=goServer__pb2.TestResponse.FromString,
                )


class GoTestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTestGO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GoTestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTestGO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestGO,
                    request_deserializer=goServer__pb2.TestRequest.FromString,
                    response_serializer=goServer__pb2.TestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'goServerTest.GoTestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GoTestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTestGO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/goServerTest.GoTestService/GetTestGO',
            goServer__pb2.TestRequest.SerializeToString,
            goServer__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
